change deployment to dockerhub instead of gh pages

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -3,6 +3,10 @@ name: Deploy Jekyll site to Pages
 on:
   push:
     branches: ["master"]
+  schedule:
+    # Schedule weekly builds on master, to ensure that the Docker image gets
+    # rebuilt regularly (in order to include security fixes in the base image).
+    - cron: '5 4 * * 5'
 
   workflow_dispatch:
 
@@ -11,39 +15,63 @@ permissions:
   pages: write
   id-token: write
 
-concurrency:
-  group: "pages"
-  cancel-in-progress: true
-
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout
-        uses: actions/checkout@v6
-      - name: Setup Ruby, JRuby and TruffleRuby
-        uses: ruby/setup-ruby@v1.320.0
+        uses: actions/checkout@v7
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
         with:
-          ruby-version: '3'
+          ruby-version: "3"
           bundler-cache: true
-          cache-version: 0
-      - name: Setup Pages
-        id: pages
-        uses: actions/configure-pages@v6
       - name: Build with Jekyll
-        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
+        run: bundle exec jekyll build
         env:
           JEKYLL_ENV: production
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v5
-
-  deploy:
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+      - name: Upload generated site
+        uses: actions/upload-artifact@v7
+        with:
+          name: jekyll-site
+          path: _site/
+          if-no-files-found: error
+  publish:
+    name: publish docker image
     runs-on: ubuntu-latest
     needs: build
+    env:
+      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
+      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
     steps:
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v5
+      - name: Download generated site
+        uses: actions/download-artifact@v8
+        with:
+          name: jekyll-site
+          path: _site/
+      - uses: actions/checkout@v7
+      - name: Fetch repository tags (for git describe to work)
+        run: git fetch --prune --unshallow
+      - name: Export env vars
+        run: |
+          set -euxo pipefail
+          export RELEASE=$(git describe --tags)
+          if [ -z "$RELEASE" ]; then echo "Could not determine release name"; exit 1; fi
+          echo "export DOCKER_TAGS='openhsr/openost:latest openhsr/openost:${RELEASE}'" >> .ci-env
+      - name: Build Docker image
+        run: | 
+          set -euxo pipefail
+          source .ci-env
+          docker build --file=./docker/Dockerfile-prod --tag=openhsr/openost .
+          for tag in $DOCKER_TAGS; do
+              docker tag openhsr/openost "$tag"
+          done
+      - name: Publish Docker image
+        run: |
+          set -euxo pipefail
+          source .ci-env 
+          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+          for tag in $DOCKER_TAGS; do
+              docker push "$tag"
+          done
